name: 'Create a binary artifact for Node on Alpine Linux'
description: 'Create a binary artifact for Node on Alpine Linux using musl'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.node-version}}
